export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';
export const GET_FORECAST_WEATHER = 'GET_FORECAST_WEATHER';
export const GET_FORECAST_WEATHER_ERROR = 'GET_FORECAST_WEATHER_ERROR';
